# Generated by Django 3.1.7 on 2021-07-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='interest',
            field=models.CharField(choices=[('Low High', 'Не важно'), ('High', 'Важно'), ('Very High', 'Очень важно')], default='Low High', max_length=15),
        ),
    ]
