# Generated by Django 3.2.5 on 2021-07-11 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='todos.category'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='interest',
            field=models.CharField(choices=[('Low', 'Не важно'), ('High', 'Важно'), ('Very High', 'Очень важно')], default=1, max_length=15),
        ),
    ]
