# Generated by Django 3.2.5 on 2021-07-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='picture',
        ),
    ]
