# Generated by Django 3.1.7 on 2021-07-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20210719_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quantity_todos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
