# Generated by Django 3.2.5 on 2021-07-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='quantity_todos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
