# Generated by Django 3.2.5 on 2021-07-31 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_remove_category_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('completed',), 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
